Update support platform doc for Apple M1 issue
actions/runner pull request #1057
Opened 2021-04-22 21:34 UTC by TingluoHuang

Update doc base on https://github.com/actions/runner/issues/1055

2021-04-22 23:08 UTC, hross commented on docs/start/envosx.md
> +The runner currently is not supported on device with Apple M1 chip.
```suggestion
The runner is currently not supported on devices with an Apple M1 chip.  
```

2021-04-22 23:09 UTC, hross commented on docs/start/envosx.md
> +We are waiting for .NET to supports it.
```suggestion
We are waiting for official .NET support. You can read more here about the [current state of support here](https://github.com/orgs/dotnet/projects/18#card-56812463).
```

2021-04-22 23:09 UTC, hross requested changes
I added some wording/formatting suggestions

2021-04-23 02:57 UTC, TingluoHuang commented
@hross Updated

2021-04-23 09:20 UTC, hross approved these changes

2021-04-23 13:47 UTC, merged