Allow container.image to be null/empty
actions/runner pull request #2025
Opened 2022-07-27 13:04 UTC by moonblade

For issue https://github.com/actions/runner/issues/265, A pull request https://github.com/actions/runner/pull/266/files was created which allows for container to be an empty string.

Since container (of type string) is an alias for container.image. It makes sense to allow container.image to have empty values as well.

Similar to the original pull request which was to allow jobs that run on public container, or no container within the same matrix, this would allow jobs that run on private container, or no container within the same matrix.

2022-09-22 23:32 UTC, webknjaz commented
It'd be nice to have the same for services.

2022-10-27 13:45 UTC, JoannaaKL requested changes

2022-10-27 13:45 UTC, JoannaaKL commented on src/Sdk/DTPipelines/workflow-v1.0.json
> +        "services-container-mapping"
```suggestion
        "container-mapping"
```

2022-10-27 13:45 UTC, JoannaaKL commented on src/Sdk/DTPipelines/workflow-v1.0.json
> +
We don't need the section 'services-container-mapping', could you please remove it? :)

2022-11-02 10:27 UTC, closed without merging