Support runner upgrade messages
actions/runner pull request #2231
Opened 2022-10-26 12:57 UTC by takost

- Added as parameter of `GetMessageAsync` runner version to get it later in the broker.
- Added new type of message `RunnerRefreshMessage`. Behaviour of update is the same, but Timeout value in new message will be number of milliseconds (int value). C# json format of the timespan looks like `d.hours:minutes:seconds.milliseconds": https://learn.microsoft.com/en-us/dotnet/core/compatibility/serialization/6.0/timespan-serialization-format#new-behavior. In other languages it can differ, so I have chosen to use more generic way to pass this value. 

Related PRs:
- [ ] [Broker PR](https://github.com/github/actions-broker/pull/206)
- [ ] [Actions PR](https://github.com/github/actions-dotnet/pull/13442)

2022-10-31 15:24 UTC, lokesh755 commented on src/Runner.Listener/Runner.cs
> +
nit: extra line

2022-10-31 15:54 UTC, TingluoHuang commented on src/Sdk/DTWebApi/WebApi/RunnerRefreshMessage.cs
> +        public int Timeout
`TimeoutInSecond`

2022-10-31 15:54 UTC, TingluoHuang commented on src/Sdk/DTWebApi/WebApi/RunnerRefreshMessage.cs
> +            this.Timeout = timeout ?? TimeSpan.FromMinutes(60).Milliseconds;
do we need milliseconds? or seconds is enough.

2022-10-31 17:00 UTC, TingluoHuang commented on src/Runner.Listener/Runner.cs
> +                                    var agentRefreshMessage = new AgentRefreshMessage(runnerUpdateMessage.AgentId, runnerUpdateMessage.TargetVersion, TimeSpan.FromMilliseconds(runnerUpdateMessage.Tim
can we merge this into the if the block on 433 so you don't have to duplicate all the code?

basically,
```C#
if (string.Equals(message.MessageType, AgentRefreshMessage.MessageType, StringComparison.OrdinalIgnoreCase) ||
    string.Equals(message.MessageType, RunnerRefreshMessage.MessageType, StringComparison.OrdinalIgnoreCase))
{
   AgentRefreshMessage runnerUpdateMessage = null;
   if (string.Equals(message.MessageType, AgentRefreshMessage.MessageType, StringComparison.OrdinalIgnoreCase))
    {
         runnerUpdateMessage = JsonUtility.FromString<AgentRefreshMessage>(message.Body);
    }
    else
    {
       var brokerRunnerUpdateMessage = JsonUtility.FromString<RunnerRefreshMessage>(message.Body); 
       runnerUpdateMessage = new AgentRefreshMessage(brokerRunnerUpdateMessage.AgentId, brokerRunnerUpdateMessage.TargetVersion, TimeSpan.FromMilliseconds(brokerRunnerUpdateMessage.Timeout));
    }

    // existing code.
}
```

2022-10-31 17:01 UTC, TingluoHuang requested changes
Might need some cleanup. 😄

2022-11-02 20:07 UTC, TingluoHuang approved these changes

2022-11-17 18:15 UTC, vmjoseph approved these changes

2022-11-21 15:17 UTC, merged